### ISSUE TITLE
How to read a field value

### ISSUE THREAD

**Issue by 123dev** [PSJira/PSJira#87] opened 2017-03-31 17:15 UTC
We just started using PSJira, thanks for sharing.

Could not figure out how to get specific field values given a Jira ID

Get-JiraIssue only returns:

- Key
- Summary
- Status
- Created

Is there a way to get more fields?
Including custom fields?

Thanks

**Comment by Clijsters** [comment] 2017-04-02 08:27
Did you looked at `Get-JiraIssue Proj-123 | Get-Member`? ;)

**Comment by 123dev** [comment] 2017-04-03 17:52
Thanks,
We're new to PSJira so were going by the wiki, didn't see any of that in the wiki.

Thanks for the help.

**Comment by Clijsters** [comment] 2017-04-03 18:37
This is more a PowerShell thing than a PSJira thing. It's typical behavior in PowerShell to output just a couple of members. This makes it more readable. I think [MSDN - Using format commands to change output view](https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/using-format-commands-to-change-output-view) gives a nice overview on this.

**Comment by 123dev** [comment] 2017-04-03 20:18
Thanks for the link,
You're right, we're new to PS as well :(

Although not related to the reported issue which thanks to you is not an issue.
How would we go debugging why we get this error 
```WARNING: JIRA returned HTTP error 500 - InternalServerError```
when invoking 
```New-JiraSession -Credential $cred```

$cred is good, as we are able to make ```Get-JiraIssue```  call without any problems.

**Comment by z0ph** [comment] 2017-04-24 15:15
@123dev Did you try -debug ?

`PS C:\Windows\system32> New-JiraSession -Credential $cred -Debug
DEBUG: [New-JiraSession] Reading Jira server from config file
DEBUG: [New-JiraSession] Created JSON syntax in variable $json.
DEBUG: [New-JiraSession] Preparing for blastoff!
DEBUG: [New-JiraSession] Converting result to JiraSession object
DEBUG: [New-JiraSession] Saving session in module's PrivateData
DEBUG: [New-JiraSession] Adding session result to existing module PrivateData
DEBUG: [New-JiraSession] Outputting result`

**Comment by Clijsters** [comment] 2017-04-24 16:05
Do you have captchas? I saw 500's in test phases where I logged on and of
several times and Jira wanted a captcha.

Am 24.04.2017 17:15 schrieb "Victor GRENU" <notifications@github.com>:

**Comment by 123dev** [comment] 2017-04-24 16:40
@z0ph 
Thanks for the follow up, here's the output with the -Debug flag

```
PS C:\Users\123dev> New-JiraSession -Credential $cred -Debug
DEBUG: [New-JiraSession] Reading Jira server from config file

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [New-JiraSession] Created JSON syntax in variable $json.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [New-JiraSession] Preparing for blastoff!

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [New-JiraSession] Encountered an exception from the Jira server: The remote server returned an error: (500)
Internal Server Error.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
WARNING: JIRA returned HTTP error 500 - InternalServerError
DEBUG: Retrieved body of HTTP response for more information about the error ($body)

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG:
public class JsonObjectTypeResolver : System.Web.Script.Serialization.JavaScriptTypeResolver
        {
          public override System.Type ResolveType(string id)
          {
            return typeof (System.Collections.Generic.Dictionary<string, object>);
          }

          public override string ResolveTypeId(System.Type type)
          {
            return string.Empty;
          }
        }

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: Converted body from JSON into PSCustomObject ($result)

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
PS C:\Users\123dev> $body
PS C:\Users\123dev> $result
PS C:\Users\123dev>
```

@Clijsters 
No captchas, just tried a new session in chrome incognito and was able to login without captcha.

**Comment by JohnLBevan** [comment] 2017-04-26 12:10
I just got the same issue as mentioned above.

i.e. `New-JiraSession -Credential $JiraCreds` has the same debug output.  The verbose ouput is:
`VERBOSE: POST https://myTenant.atlassian.net/rest/auth/1/session with -1-byte payload`

However, `Get-JiraIssue -Credential $JiraCreds -Key 'SB-42'` works as expected.

I suspect the issue is I'm using Jira Cloud, which uses the new Atlassian ID logon system.  Perhaps that's changed something (though there's no mention in the documentation from September last year): https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-cookie-based-authentication/

Also, there is currently an open issue related to the recent security breach.  I see the first occurrence of the `HTTP 500` error was logged 23 days ago, so likely isn't related; but maybe that's the cause for anyone getting this issue in the past few days if different to the above?
https://atlassian.statuspage.io/incidents/kz9n65qlcljd

**Comment by lipkau** [comment] 2017-05-22 10:22
I have tested this with my Jira cloud instance.

This is what I got either with wrong credentials, or before adding my user to the group `jira-core-users`:
```powershell
I ♥ PSNew-JiraSession -Credential (Get-Credential) -verbose
VERBOSE: POST https://psjira.atlassian.net/rest/auth/1/session with -1-byte payload
WARNING: JIRA returned HTTP error 401 - Unauthorized
```
and this with correct ones and in the group `jira-core-users`:
```powershell
I ♥ PSNew-JiraSession -Credential (Get-Credential) -verbose
VERBOSE: POST https://psjira.atlassian.net/rest/auth/1/session with -1-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8

Username WebSession                                      JSessionID               LoginInfo
-------- ----------                                      ----------               ---------
admin    Microsoft.PowerShell.Commands.WebRequestSession J0GxOfH4C0EU0V07LD2vRA00
```

I am not able to reproduce your error and have found nothing about captchas.
Is this still a problem or where you able to fix it?

**Comment by 123dev** [comment] 2017-05-23 19:20
> I have tested this with my Jira cloud instance.
> This is what I got either with wrong credentials, or before adding my user to the group jira-core-users:

We're also on Jira cloud.
I'm admin / site-admin, so I doubt that the HTTP 500 error is a permission related error (HTTP 401 is)
Besides we don't have such group as jira-core-users, we're on Jira Software, which is basically Jira Core + Jira Agile.

**Comment by lipkau** [comment] 2017-05-23 19:41
did you retrieve the `$body` of the debug?

HTTP 500 means the request got to the server, but the server was unable to process it (bad json, wrong fields, etc)

**Comment by 123dev** [comment] 2017-05-23 20:53
@lipkau 

If you look at my earlier post with -Debug, you'd see that I was getting http 500 with $body evaluating to blank.

JohnLBevan Also reported the same issue

Interestingly Now I'm getting http 401, so things might have changed at the backend, probably they were not handling @ in the username (see below) and the server was returning http 500.

Did some digging,
It's working with Get-Jira-Issue because Get-Jira-Issue is using Basic Authentication.
It's not working with Cookie Based authentication because the endpoint doesn't accept email as a username field.
https://jira.atlassian.com/browse/ID-6270

Using the username worked.

The issue can be closed,
Perhaps an enhancement to change the New-JiraSession to call using Basic Authentication or oAuth and grab the cookie that way as suggested here.
https://jira.atlassian.com/browse/JRACLOUD-65166

**Comment by lipkau** [comment] 2017-05-24 04:56
Thank you for investigating.

We should implement the Basic Authentication. The OAuth is already being tracked in #101.

**Comment by lipkau** [comment] 2017-05-24 09:35
hm... @123dev 
I have tried authenticating with my email address on my JIRA cloud instance, and it worked fine.
http://img03.imgland.net/8p-Ms-Z.png

**Comment by lipkau** [comment] 2017-05-24 11:51
I was able to reproduce the problem.

I used incorrect credentials 30 times in order to trigger the captcha (which #107 is catching fine).
However, I am unable to get the header with the captcha information to reset, as when I login on the website I do not get a captcha.

I have asked the Atlassian support for help: https://getsupport.atlassian.com/servicedesk/customer/portal/23/JST-288856

**Comment by lipkau** [comment] 2017-05-24 11:53
I prefer to continue any discussion/debugging of this in #107, as the original question of this issue has been answered a long time ago.

I am closing this issue now.

**Closed by lipkau** 2017-05-24 11:53 UTC
Labels: enhancement, ready, up-for-graps
